#this is a simple weather app to check the weather of a specified region.
#this idea and code was generated by chatGPT, modified by me to actually work, just a some small details missed

import requests
import json

# Enter your OpenWeatherMap API key here
#I added the key, not the AI
API_KEY = "OpenWeatherMap_API_key_here"

# Enter the location for which you want to view the weather
city = "Lee's Summit, US"

# Construct the API request URL
url = "https://api.openweathermap.org/data/2.5/weather?q={}&appid={}".format(city, API_KEY)

# Send the API request and get the response
response = requests.get(url)

# Parse the response as JSON
data = json.loads(response.text)
# print(data)

# Get the current temperature and convert it to Fahrenheit
#error here no key called 'main', possibly because the api key isnt active yet, still had no catch for that
temp_kelvin = data["main"]["temp"]
temp_fahrenheit = (temp_kelvin - 273.15) * 9/5 + 32

# Get the current weather conditions
weather = data["weather"][0]["description"]

# Print the current temperature and weather conditions
print("The current temperature in {} is {}°F and {}".format(city, temp_fahrenheit, weather))
