#this idea and code was generated by chatGPT, units tests for the generated weather app

import unittest

# Import the weather application code
from weather_app import *

class WeatherAppTestCase(unittest.TestCase):
    def test_api_key(self):
        # Test that the API_KEY variable is set
        self.assertIsNotNone(API_KEY)
    
    def test_city(self):
        # Test that the city variable is set
        self.assertIsNotNone(city)

    def test_api_request(self):
        # Test that the API request URL is correct
        expected_url = "https://api.openweathermap.org/data/2.5/weather?q={}&appid={}".format(city, API_KEY)
        self.assertEqual(url, expected_url)

    def test_api_response(self):
        # Test that the API response is valid JSON
        self.assertIsNotNone(response)
        try:
            json.loads(response.text)
        except json.JSONDecodeError:
            self.fail("API response is not valid JSON")

   
